### ISSUE TITLE
create component interface

### ISSUE THREAD

**Issue by anasrul03** [anasrul03/cine-search#1]
**1. Logo.jsx - @wenfayeee 
2. Search.jsx - @Vinothinni 
3. MovieCard.jsx - @anasrul03 
4. MovieDetails.jsx - @Amarnath911** 

5. LatestMovies.jsx
6. PopularMovies.jsx

**Comment by munnfaye** [comment]
Updated task list

1. MovieCard.jsx - @anasrul03 
2. MovieDetails.jsx - @Amarnath911 
3. MainPage.jsx - @wenfayeee 
4. Header / Footer / Search - @Vinothinni
